"""Invariant templates -> a complete, compile-checked hypothesis test module."""
from groundwork.core.runner import ToolError
from groundwork.tools.propcheck.strategies import strategy_expr

_INVARIANTS = ("roundtrip", "idempotent", "oracle", "never_raises")


def _sym(dotted: str) -> tuple[str, str]:
    """('pkg.mod.name') -> ('pkg.mod', 'name')."""
    mod, _, name = dotted.rpartition(".")
    if not mod or not name:
        raise ToolError("USAGE", f"expected module.name, got {dotted!r}",
                        exit_code=2)
    return mod, name


def generate_property(*, invariant: str, module: str, func: str, strategy: str,
                      inverse: str | None = None, reference: str | None = None,
                      name: str | None = None) -> str:
    if invariant not in _INVARIANTS:
        raise ToolError("USAGE", f"invariant must be one of {_INVARIANTS}, "
                                 f"got {invariant!r}", exit_code=2)
    strat = strategy_expr(strategy)
    imports = [f"from {module} import {func}"]
    body_name = name or f"test_{invariant}_{func}"

    if invariant == "roundtrip":
        if not inverse:
            raise ToolError("USAGE", "roundtrip requires --inverse module.name",
                            exit_code=2)
        imod, inv = _sym(inverse)
        imports.append(f"from {imod} import {inv}")
        assertion = f"assert {inv}({func}(x)) == x"
    elif invariant == "idempotent":
        assertion = f"assert {func}({func}(x)) == {func}(x)"
    elif invariant == "oracle":
        if not reference:
            raise ToolError("USAGE", "oracle requires --reference module.name",
                            exit_code=2)
        rmod, ref = _sym(reference)
        imports.append(f"from {rmod} import {ref}")
        assertion = f"assert {func}(x) == {ref}(x)"
    else:  # never_raises
        assertion = f"{func}(x)  # must not raise"

    import_block = "\n".join(dict.fromkeys(imports))  # dedupe, keep order
    src = (
        f'"""Property test generated by groundwork propcheck ({invariant}).\n'
        f'Committed and run in CI via verify/pytest; edit freely."""\n'
        "from hypothesis import given, settings, strategies as st\n"
        f"{import_block}\n\n\n"
        "@settings(derandomize=True)\n"
        f"@given(x={strat})\n"
        f"def {body_name}(x):\n"
        f"    {assertion}\n"
    )
    try:
        compile(src, "<generated>", "exec")
    except SyntaxError as e:
        raise ToolError("GEN_ERROR", f"generated code does not compile: {e}",
                        exit_code=1) from e
    return src
